### PR TITLE
Prevent thaum items with invalid metadata from crashing clients

### PR DESCRIPTION
**Pull request by rndmorris**

### CODE REVIEW

**Comment by rndmorris** [comment]
Actually, there are a few other items susceptible to the same `ArrayIndexOutOfBoundsException` crash if created with invalid metadata (`ItemNugget` and `ItemResource`). I'm tempted to just lump those in with this one under a single `itemMetadataCrash` setting.

Thoughts?

**Comment by Midnight145** [comment]
Yeah that would work

What would honestly be easier/cleaner, if it's all exactly the same issue, is to just write an asm transformer for it, but that might not be worth the effort

**Review by Midnight145 — APPROVED** [review]
Approved, but I won't merge it yet in case you want to do the others under the same PR

**Comment by rndmorris** [comment]
> Yeah that would work
> 
> What would honestly be easier/cleaner, if it's all exactly the same issue, is to just write an asm transformer for it, but that might not be worth the effort

So long as all of your target classes have the same shape you try to use in your mixin class (e.g. all have an `IIcon[] icon` field, all have a `getIconFromDamage(int)` method, etc), it's surprisingly flexible. It almost feels like it allows duck-typing.

**Comment by Midnight145** [comment]
This likely needs Hodgepodge compat, from when I was looking earlier it fixes some of the same things, including the exact same duck typing solution for the iicon fix. I can double check here in a bit if you want

**Comment by rndmorris** [comment]
Does it? Oops. The only part of Hodgepodge I've looked at was that link to its Mixins enum you sent me.

**Review by Midnight145 — APPROVED** [review]
Double checked hodgepodge, it changes something else that mixins in a bunch of classes, not this so we're good

**Pull request merged**
